### ISSUE TITLE
nixery.dev registry is down

### ISSUE THREAD

**Issue by mkmik** [tazjin/nixery#138]
FYI:
```console
$ docker pull nixery.dev/shell
Using default tag: latest
Error response from daemon: received unexpected HTTP status: 500 Internal Server Error
```

**Comment by mkmik** [comment]
@tazjin 

This was fixed but now it (or something similar) happened again:

```
  Warning  Failed     21s (x2 over 77s)  kubelet            Failed to pull image "nixery.dev/shell/findutils/gnugrep/gnutar/hexdump/less/mount/procps/curl/grpcurl/binutils/gdb/strace/rustc/linuxpackages.perf/perf-tools/gzip/zstd": rpc error: code = Unknown desc = Error response from daemon: received unexpected HTTP status: 500 Internal Server Error
```

**Comment by tazjin** [comment]
It's possible that you ran a command in the middle of a restart (which only take a few seconds); with the setup we have right now the number of restarts is unfortunately pretty high.

We have a [tracking bug](https://b.tvl.fyi/issues/138) for this in the TVL infrastructure and I'll attempt to prioritise it soon.

**Comment by mkmik** [comment]
Thanks

**Comment by tazjin** [comment]
Quick update: As of [cl/4064](https://cl.tvl.fyi/c/depot/+/4064/) the frequency of config changes for Nixery is going to be reduced significantly, which should make occurrences of this much less frequent.

Do note however that nixery.dev is provided without any SLO at the moment.

**Comment by mkmik** [comment]
> Do note however that nixery.dev is provided without any SLO at the moment.

Thanks for running it!

(I have it in my backlog to self-host it somewhere, call me lazy but I'm just waiting until the self-hosting docs are more fleshed out :-) )

**Comment by tazjin** [comment]
Do you use NixOS? At TVL we have a module for it which you might be able to adapt pretty easily: https://cs.tvl.fyi/depot/-/blob/ops/modules/nixery.nix

**Comment by mkmik** [comment]
No I don't use nixos yet; always wanted to find a good excuse to play with it; I guess I just found one! :-)
