### ISSUE TITLE
nixery.dev - package in unstable and 22.05 missing

### ISSUE THREAD

**Issue by 06kellyjac** [tazjin/nixery#153]
`Could not find Nix packages: [tracee]`

Is it visible which commit nixery.dev is using? I had a quick scan through TVL but didn't spot anything

Does it need updating?

**Comment by tazjin** [comment]
Hey! The commit is in our Niv pin: [//third_party/sources/sources.json](https://cs.tvl.fyi/depot/-/blob/third_party/sources/sources.json?L50-61)

We actually updated the channel a few hours ago, but it is not yet deployed - gonna prod that now.

**Comment by tazjin** [comment]
Update done, and it seems like it introduced the package you need:

```
tazjin@whitby /depot (canon)> sudo docker pull nixery.dev/shell/tracee
Using default tag: latest
latest: Pulling from shell/tracee
<blabla>
Digest: sha256:a7bf7749f2469bd0b6e2bfbc4918abde6dc0226f77ea5172354f7e9582e78373
Status: Downloaded newer image for nixery.dev/shell/tracee:latest
nixery.dev/shell/tracee:latest
```

**Comment by tazjin** [comment]
This issue motivated me to write: https://cl.tvl.fyi/c/depot/+/5881/

Once we've submitted that, the current deployed commit will be displayed on nixery.dev
