### ISSUE TITLE
Error 500 : internal error (ansible-core)

### ISSUE THREAD

**Issue by rivoalrivoal** [tazjin/nixery#159]
Hello,

For the past few hours (14:00 UTC), when I try to pull the image using ansible-core, I'm getting a 500 error:

```bash
docker pull nixery.dev/shell/python311/python311packages.ansible-core
Using default tag: latest
Error response from daemon: received unexpected HTTP status: 500 Internal Server Error
```

Around 9:00 UTC, we were able to use this image without any issues.

Do you have any insights into this issue?

Thank you!

**Comment by tazjin** [comment]
Hey! A `nixpkgs` update rolled out earlier today, I'm checking if that is related now.

**Comment by tazjin** [comment]
It seems like that is the case, there's some dependency of `ansible-core` called `rednose` that was updated and is failing to build: https://gist.github.com/tazjin/7d837775e2ecf870b04e54e15c7abf65

It seems like it's a plugin only for tests that is adding colour to test outputs, which seems like a pretty silly thing to fail an entire build on. I don't think we can do much about it right now other than roll-forward and hope it gets fixed soon upstream.

The other alternative is disabling tests, but that will cause the whole package to rebuild (Nix won't cache it without the tests), which will probably hit time limits (as nixery.dev is a free service it doesn't have unlimited resources available).

I've kicked off a CI build with a nixpkgs bump, if it succeeds we'll merge it and roll it out - maybe there's a fix in it already.

**Comment by tazjin** [comment]
Also want to add about the error message you're seeing: The Docker registry protocol unfortunately doesn't let us feed back a better error message :(

**Comment by rivoalrivoal** [comment]
I would like to thank you for your prompt response.

For now, i use "python3/python3packages.ansible-core", which corresponds to version 3.10 of python (WTF?) and it works !  👍

**Comment by tazjin** [comment]
@rivoalrivoal Interesting! So the bug in that package is probably just with a specific Python version. I'll see if I can pin Nixery to the stable channel (it's following our unstable channel atm), that might make things better.

**Comment by rivoalrivoal** [comment]
Yes, i think it's only for Python 3.11.

**Comment by tazjin** [comment]
Nixery is now [using the stable channel](https://cl.tvl.fyi/c/depot/+/9126), and this package works there.
