### ISSUE TITLE
nixery.dev is down

### ISSUE THREAD

**Issue by hantusk** [tazjin/nixery#167]
nixery.dev is down with a 502 bad gateway, hope it will come back up again :)

**Comment by tazjin** [comment]
Whelp, the GC on the backing instances broke and the disks filled up. I'm fixing it now properly.

It seems like my alerting went into `/dev/null`, sorry about that.

**Comment by tazjin** [comment]
Closing this for now, will redo the alerting in the background. GC has been fixed and should be working properly now, so this particular issue won't reoccur.
