### ISSUE TITLE
nixery.dev down

### ISSUE THREAD

**Issue by 80imike** [tazjin/nixery#168]
nixery.dev down

 curl https://nixery.dev/ -vI
*   Trying 51.250.51.78:443...
* connect to 51.250.51.78 port 443 failed: Connection timed out
* Failed to connect to nixery.dev port 443 after 134355 ms: Connection timed out
* Closing connection 0

**Comment by tazjin** [comment]
![nixery_metrics](https://github.com/user-attachments/assets/03916467-9be1-457f-a800-419e9c24cf7b)

Something's gone haywire on the machine, I'm investigating, kind of unclear what it's doing.

**Comment by tazjin** [comment]
Restarting the box did resolve it in the end yesterday, didn't fully figure out what happened, my best theory is that Nix's GC got stuck on something.
